-- 022_cards_ip_limit: 为 cards 表添加 IP 限制列
ALTER TABLE cards ADD COLUMN IF NOT EXISTS enable_ip_limit BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS max_ips INTEGER NOT NULL DEFAULT 1;
